spring:
  application:
    name: digital-banking
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_banking_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.security: TRACE